name: User Input with Checkboxes
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: User Input
        id: input
        uses: actions/toolkit@v2.x
        with:
          path: |
            Please select one or more options:
            [ ] Option 1
            [ ] Option 2
            [ ] Option 3
            [ ] Option 4
            [ ] Option 5
      - name: Check Options
        run: |
          echo "You selected:"
          for option in ${{ steps.input.outputs.result }}; do
            echo "- $option"
          done
