name: User Input with Checkboxes
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: User Input
        run: |
          echo "Please select one or more options:"
          echo "[ ] Option 1"
          echo "[ ] Option 2"
          echo "[ ] Option 3"
          echo "[ ] Option 4"
          echo "[ ] Option 5"
          read -p "Enter your selection (comma-separated): " selection
          echo "You selected: $selection"
        env:
          SELECTION: ${{ steps.user_input.outputs.selection }}
      - name: Check Options
        if: contains(env.SELECTION, 'Option 1')
        run: echo "Option 1 selected"
      - name: Check Options
        if: contains(env.SELECTION, 'Option 2')
        run: echo "Option 2 selected"
      - name: Check Options
        if: contains(env.SELECTION, 'Option 3')
        run: echo "Option 3 selected"
      - name: Check Options
        if: contains(env.SELECTION, 'Option 4')
        run: echo "Option 4 selected"
      - name: Check Options
        if: contains(env.SELECTION, 'Option 5')
        run: echo "Option 5 selected"
